- name: install redis-server
  apt: pkg=redis-server state=present
  sudo: yes
  tags:
    - master
    - redis_server

- name: configure redis file
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf
  sudo: yes
  tags:
    - master
    - redis_server
  notify: restart redis
