do ->
  # isso daqui tem que ta no html, mas to botando aqui so pra salvar esse codigo
  # atualmente nao esta sendo utilizado em canto nenhum
  translations = publications:
    zero: '<%= t \'.publications.zero\' %>'
    one: '<%= t \'.publications.one\' %>'
    other: '<%= t \'.publications.other\' %>'

  data = $('.load-publications').toArray().map((i) ->
    {
      provider: i.getAttribute('data-provider')
      id: i.getAttribute('data-id')
    }
  )
  if data.length
    $.ajax
      method: 'post'
      url: '/api/es/get_publications_count'
      dataType: 'json'
      contentType: 'application/json'
      data: JSON.stringify(data: data)
      success: (resp) ->
        resp.forEach (d) ->
          html = undefined
          if d['count'] == 0
            html = translations.publications.zero
          else if d['count'] == 1
            html = translations.publications.one
          else
            html = translations.publications.other.replace('{{count}}', d['count'])
          $('.load-publications').filter(->
            @getAttribute('data-provider') == d['provider'] and @getAttribute('data-id') == d['id']
          ).html html
          return
        return
      error: ->
        alert 'houve um erro ao carregar a quantidade de posts da sua rede social'
        return
  return

# ---
# generated by js2coffee 2.2.0
