- name: Install nginx
  apt: pkg=nginx state=latest
  sudo: yes

- name: Remove the default app
  command: rm -rf /etc/nginx/sites-enabled/default
  sudo: yes

- name: Configure nginx for the template
  template: src=template.conf.j2 dest=/etc/nginx/sites-enabled/template group=www-data owner=www-data force=yes
  sudo: yes

- name: Restart nginx
  action: service name=nginx state=restarted
  sudo: yes

