# Common prereqs (e.g. build tools, libs)
- include: common-prereqs.yml

# rbenv setup
- include: rbenv-setup.yml

# Common ruby environment tasks (e.g. adding a .gemrc, ...)
- include: common-post.yml

